### ISSUE TITLE
Access Transmission from LAN

### ISSUE THREAD

**Issue by gsdovali** [maorcc/hassio-addon-transmission#15]
when open http://IPOFHASSIO:9091 from other computer from LAN it does not work.
Is port 9091 closed?

**Comment by maorcc** [comment]
Make sure that you have port 9091 exposed in the addon Configuration page.
Like this:

![image](https://github.com/maorcc/hassio-addon-transmission/assets/255973/6d3659d0-e2e8-479e-b682-38d58d3ce1ab)

**Comment by gsdovali** [comment]
thanks

**Comment by gsdovali** [comment]
this is working
