### ISSUE TITLE
no inicia - bug

### ISSUE THREAD

**Issue by tetradog** [maorcc/hassio-addon-transmission#31]
Error relocating /lib/libcrypto.so.3: : symbol not found
s6-linux-init-shutdownd: warning: /run/s6/basedir/scripts/rc.shutdown was killed by signal 11

V4.0.6

Home Assistant

Core
2024.10.3
Supervisor
2024.10.3
Operating System
13.2
Frontend
20241002.3

instalado en Raspberry pi 4 2GB 

antes funcionaba bien pero no se si se ha bugeado al actualizar el home assistant o es otra cosa...

**Comment by maorcc** [comment]
Where do you see this error? Is it still happening?

**Comment by tetradog** [comment]
It’s working fine now. I uninstalled and reinstalled it, and I may have updated it a few days ago. It seems to be working again. :)


Thank you for your attention.
